version: "3"
#uses on github action
services:
  mongo:
    image: mongo
    ports:
      - 27018:27017 # for access
    networks:
      - back
    restart: always
    tty: true
    container_name: descriptors-wallet_mongo

  api:
    build: ./
    ports:
      - 3000:3000
    depends_on:
      - "mongo"
    networks:
      - back
    restart: always
    tty: true
    container_name: descriptors-wallet_api

volumes:
  db_data:


networks:
  back:
    external: true
  front:
    external: true
